### ISSUE TITLE
v1.13 Deprecations Tracking Issue

### ISSUE THREAD

**Issue by dstaley** [dstaley/ember.js#1]
This is a list of all the deprecations in the 1.13.x series. Items without checks need to have a `url` property added to the `options` param in the call to `Ember.deprecate`. The URL should correspond to an entry in the [deprecations list](https://github.com/dstaley/website/blob/master/source/deprecations/v1.x.html.md). Once added, we can mark them as done.

If there's already a link to a deprecation notice, leave a comment so I can mark it as done.
### 1.13.6
- [ ] [#11900](https://github.com/emberjs/ember.js/pull/11900) Deprecate Ember.Handlebars.makeViewHelper.
- [ ] [#11900](https://github.com/emberjs/ember.js/pull/11900) Deprecate Ember.HTMLBars.makeViewHelper.
- [ ] [#11900](https://github.com/emberjs/ember.js/pull/11900) Deprecate Ember.HTMLBars._registerHelper (manual registration is no longer needed).
- [ ] [#11900](https://github.com/emberjs/ember.js/pull/11900) Deprecate Ember.HTMLBars.makeBoundHelper in favor of Ember.Helper.helper.
- [ ] [#11900](https://github.com/emberjs/ember.js/pull/11900) Deprecate Ember.Handlebars.makeBoundHelper in favor of Ember.Helper.helper.
- [ ] [#11900](https://github.com/emberjs/ember.js/pull/11900) Deprecate Ember.Handlebars.registerBoundHelper in favor of Ember.Helper.helper.
- [ ] [#11900](https://github.com/emberjs/ember.js/pull/11900) Deprecate Ember.Handlebars.helper in favor of Ember.Helper.helper and automatic helper resolution.
- [ ] [#11900](https://github.com/emberjs/ember.js/pull/11900) Deprecate Ember.Handlebars.registerHelper in favor of Ember.Helper.helper and automatic helper resolution.
- [ ] [#11826](https://github.com/emberjs/ember.js/pull/11826) Deprecate Ember.ContainerView
- [ ] [#11891](https://github.com/emberjs/ember.js/pull/11891) Deprecate Ember.CollectionView
- [ ] [#11934](https://github.com/emberjs/ember.js/pull/11934) Deprecate specifying positionalParams at extend time in favor of using static factory properties.
### 1.13.5
- [ ] [#11767](https://github.com/emberjs/ember.js/pull/11767) Deprecate Controller#needs
- [ ] [#11468](https://github.com/emberjs/ember.js/pull/11468) Deprecate Ember.Freezable and frozenCopy.
- [ ] [#11765](https://github.com/emberjs/ember.js/pull/11765) Mark Ember.oneWay as deprecated
- [ ] [#11778](https://github.com/emberjs/ember.js/pull/11778) Deprecate reverse argument ordering in Ember.observer.
- [ ] [#11787](https://github.com/emberjs/ember.js/pull/11787) Deprecate slash for a namespace in the {{render}} helper.
- [ ] [#11798](https://github.com/emberjs/ember.js/pull/11798) Deprecate Function#observesBefore.
- [ ] [#11812](https://github.com/emberjs/ember.js/pull/11812) Add deprecation messages when using Ember.get / Ember.set in a certain ways.
### 1.13.3
- [ ] [#11510](https://github.com/emberjs/ember.js/pull/11510) Deprecate Ember.Object.createWithMixins.
- [ ] [#11512](https://github.com/emberjs/ember.js/pull/11512) Deprecate Ember.oneWay in favor of Ember.computed.oneWay.
- [ ] [#11511](https://github.com/emberjs/ember.js/pull/11511) Deprecate Ember.keys in favor of Object.keys.
- [ ] [#11511](https://github.com/emberjs/ember.js/pull/11511) Deprecate Ember.create in favor of Object.create.
### 1.13.1
- [ ] [#11464](https://github.com/emberjs/ember.js/pull/11464) Deprecate Ember.immediateObserver.
- [ ] [#11476](https://github.com/emberjs/ember.js/pull/11476) Deprecate Ember.ArrayController.
- [ ] [#11478](https://github.com/emberjs/ember.js/pull/11478) Deprecate Ember.RenderBuffer.
### 1.13.0
- [ ] [#11279](https://github.com/emberjs/ember.js/pull/11279) Deprecate {{#each foo in bar}}{{/each}}.
- [ ] [#11286](https://github.com/emberjs/ember.js/pull/11286) Deprecate Ember.EnumerableUtils.
- [ ] [#11313](https://github.com/emberjs/ember.js/pull/11313) Allow deprecated access to template in component to determine if a block was provided.
- [ ] [#11387](https://github.com/emberjs/ember.js/pull/11387) Deprecate Ember.View.
- [ ] [#11389](https://github.com/emberjs/ember.js/pull/11389) Deprecate {{view}} helper.
- [ ] [#11394](https://github.com/emberjs/ember.js/pull/11394) Add Ember.LinkComponent and deprecate Ember.LinkView.
- [ ] [#11400](https://github.com/emberjs/ember.js/pull/11400) Deprecate Ember.computed.any.
- [ ] [#11416](https://github.com/emberjs/ember.js/pull/11416) Deprecate Ember.Select.
- [ ] [#11403](https://github.com/emberjs/ember.js/pull/11403) Deprecate Ember.arrayComputed, Ember.ReduceComputedProperty, Ember.ArrayComputedProperty, and Ember.reduceComputed.
- [ ] [#11401](https://github.com/emberjs/ember.js/pull/11401) Deprecate {{view and {{controller template local keywords.

**Comment by wifelette** [comment]
@dstaley Would love your help with https://github.com/emberjs/website/issues/2256 if you're up for it :) Feel free to add the commit links there, if it seems useful. For now I just have the item listed with the PR if someone's already tackled/tackling it. 

Going to try and get more help on this this week.
